### ISSUE TITLE
Bot hangs when using /regex

### ISSUE THREAD

**Issue by MoonTM-GIT** [Java-Discord/JavaBot#146]
When using the /regex command with some regex patterns the bot stops responding to any other commands and starts missing heartbeats. This happens because the pattern the user put it takes a very long time to calculate which in turn hangs the bot.

**Comment by danthe1st** [comment]
This problem is known as ReDOS and caused by Java's implementation of regex matching.

Regex matching is not responsive to interruption or similar so it cannot be stopped using a timeout (except using `Unsafe` or `Thread#stop`).

**Comment by danthe1st** [comment]
There is [a draft JEP](https://openjdk.java.net/jeps/8260688) and an [OpenJDK issue](https://bugs.openjdk.java.net/browse/JDK-8260688) for building a ReDOS-safe regex into the JVM. However, this might not be implemented any time soon (and the bot would still need to update to that java version).
The JEP also mentions re2 (a C++ implementation of Thompson NFA (a ReDOS-safe Regex algorithm)) and re2-java (an unmaintained java port of re2).
It might be possible to use re2-java or an existing Thompson NFA implementation like [re2j (pure Java port of re2) from Google](https://github.com/google/re2j) in order to fix this problem.
