### ISSUE TITLE
Improve Auto mod to detect phishing links

### ISSUE THREAD

**Issue by MoonTM-GIT** [Java-Discord/JavaBot#86]
e.g. _and probably most important for now_ links looking like discord.com that aren't real

Could also include a general list of known phishing links

**Comment by danthe1st** [comment]
For links that look like `discord.com`, the levenshtein distance could be used. But in my opinion, checking for known phishing domains might be better because it would allow other non-discord-like phishing domains to be blocked and typing `discord.com` wrong will not result in the automod being triggered. Also, blocking domains looking similar to `discord.com` might result in domains like `discordapp.com` (someone might still think of that being the correct one) or similar getting blocked.
